/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  InitializableClones,
  InitializableClonesInterface,
} from "../InitializableClones";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "instance",
        type: "address",
      },
    ],
    name: "Deployed",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "master",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "initializer",
        type: "bytes",
      },
    ],
    name: "clone",
    outputs: [
      {
        internalType: "address",
        name: "instance",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class InitializableClones__factory {
  static readonly abi = _abi;
  static createInterface(): InitializableClonesInterface {
    return new utils.Interface(_abi) as InitializableClonesInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): InitializableClones {
    return new Contract(address, _abi, signerOrProvider) as InitializableClones;
  }
}
